apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol-agent
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.159.1
    helm:
      releaseName: otelcol-agent
      valueFiles:
      - $values/kubernetes/argocd/configs/otelcol/agent-values.yaml
  - repoURL: https://github.com/mwimpelberg28/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: otelcol
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
